In [2]:
import pandas as pd
import MySQLdb

In [3]:
db = MySQLdb.connect("thinkprodmysql.cpqeziuyg4wm.us-west-2.rds.amazonaws.com","dbview","dbview@13972684","engage_v1" )
db.autocommit=False

In [4]:
df = pd.read_sql_query(sql="""
SELECT 
    *
FROM
    engage_v1.survey_v1_user_response_store
        JOIN
    survey_v1_option ON survey_v1_option.OPT_ID = survey_v1_user_response_store.OPTION_ID
        JOIN
    survey_v1_question ON survey_v1_question.QUESTION_ID = survey_v1_user_response_store.QUESTION_ID limit 100;""",con=db)
df.head()

,USR_RES_ST_ID,USER_SURVEY_DEF_ID,PUM_ID,QUESTION_ID,OPTION_ID,FIELD_VALUE,COMMENT,OPT_ID,OPT_ORDER,OPT_TEXT,...,QUESTION_TEXT,QUESTION_TYPE,QUESTION_TIPS,QUESTION_ORDER,QUESTION_DIRECTION,REG_EXP_ID,DATA_SET_ID,SECTION_ID,PAGE_ID,FILTER_NAME
0,1841,3766,None,271,70,None,,70,1,Strongly Agree,...,<p>The organization makes it sufficiently clea...,QUESTION_SCALE,,1,V,None,9,None,32,None
1,1842,3766,None,272,70,None,,70,1,Strongly Agree,...,<p>The organization makes it sufficiently clea...,QUESTION_SCALE,,2,V,None,9,None,32,None
2,1843,3766,None,273,70,None,,70,1,Strongly Agree,...,<p>The organization makes it sufficiently clea...,QUESTION_SCALE,,3,V,None,9,None,32,None
3,1844,3766,None,274,70,None,,70,1,Strongly Agree,...,<p>My supervisor sets a good example in terms ...,QUESTION_SCALE,,4,V,None,9,None,32,None
4,1845,3766,None,275,70,None,,70,1,Strongly Agree,...,<p>My supervisor would never authorize unethic...,QUESTION_SCALE,,5,V,None,9,None,32,None

In [10]:
df.groupby(["QUESTION_TEXT"]).USR_RES_ST_ID.mean().plot("bar")

ImportError: No module named 'matplotlib'